Local-Guide-App/Controllers/HomeController.cs
using Local_Guide_App.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Local_Guide_App.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var locations = db.Locations.ToList();

            var locationDtos = locations.Select(location => new LocationDto
            {
                LocationId = location.LocationId,
                LocationName = location.LocationName,
                LocationDescription = location.LocationDescription,
                Category = location.Category,
                Address = location.Address,
                CreatedDate = location.CreatedDate,
                AverageRating = location.Reviews.Any() ? Math.Round(location.Reviews.Average(r => r.Rating), 2) : 0,
                LocationHasPic = location.LocationHasPic,
                PicExtension = location.PicExtension,
            }).ToList();

            return View(locationDtos);
        }

        public ActionResult About()
        {
            ViewBag.Message = "A CMS for local guides to share information about attractions, restaurants, events, and services in their area.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Local-Guide-App/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Mvc;
using Local_Guide_App.Models;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;
using System.Web;
using System.Diagnostics;
using System.Net;
using System.Net.Http.Headers;

namespace Local_Guide_App.Controllers
{
    public class LocationController : Controller
    {

        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static LocationController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44395/api/locationdata/");
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(Location location)
        {
            string url = "AddLocation";
            location.CreatedDate = DateTime.Now;

            string jsonpayload = jss.Serialize(location);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;

            Debug.WriteLine("==>>>"+response.IsSuccessStatusCode);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                // Handle specific bad request (e.g., ModelState errors) if needed
                return View("Add", location); // Return to the add view with model errors
            }
            else
            {
                // Handle other status codes (e.g., 500 Internal Server Error)
                return RedirectToAction("Error");
            }
        }

        public ActionResult List()
        {
            string url = "ListLocations";
            HttpResponseMessage response = client.GetAsync(url).Result;

            IEnumerable<LocationDto> locations = response.Content.ReadAsAsync<IEnumerable<LocationDto>>().Result;
            return View(locations);
        }

        public ActionResult LocationWithReviews(int id)
        {
            string url = $"ListReviewsForLocation/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                LocationWithReviewsDto locationWithReviews = response.Content.ReadAsAsync<LocationWithReviewsDto>().Result;
                return View(locationWithReviews);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            string url = $"FindLocation/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                LocationDto selectedLocation = response.Content.ReadAsAsync<LocationDto>().Result;
                return View(selectedLocation);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Update(LocationDto location, HttpPostedFileBase LocationPic)
        {
            string url = $"UpdateLocation/{location.LocationId}";
            location.CreatedDate = DateTime.Now; // Assuming you want to update the CreatedDate as well

            string jsonpayload = jss.Serialize(location);

            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                if (LocationPic != null && LocationPic.ContentLength > 0)
                {
                    url = $"UploadLocationPic/{location.LocationId}";
                    MultipartFormDataContent multipartContent = new MultipartFormDataContent();
                    multipartContent.Add(new StreamContent(LocationPic.InputStream), "LocationPic", LocationPic.FileName);

                    response = client.PostAsync(url, multipartContent).Result;

                    if (!response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Error");
                    }
                }

                return RedirectToAction("Details", new { id = location.LocationId });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Location/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id)
        {
            string url = $"DeleteLocation/{id}";

            // Assuming you have configured HttpClient properly
            var response = client.PostAsync(url, null).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else if (response.StatusCode == HttpStatusCode.NotFound)
            {
                return HttpNotFound();
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Details(int id)
        {
            string url = $"FindLocation/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                LocationDto location = response.Content.ReadAsAsync<LocationDto>().Result;
                return View(location);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

Local-Guide-App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h1 id="title" class="text-center">@ViewBag.Title</h1>
    <h3 class="text-center text-muted col-md-8 offset-md-2">@ViewBag.Message</h3>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <p>
                    Inspired by my passion for being a Google Local Guide and sharing reviews and photos of various locations,
                    I aim to develop a Local Guide web app. This app will serve as a platform for users to discover and explore local attractions,
                    restaurants, events, and services through the eyes of fellow community members. Users can contribute by adding new locations,
                    writing reviews, uploading photos, and sharing their experiences. The app will emphasize community engagement and collaboration,
                    empowering users to make informed decisions about where to go and what to do based on authentic, user-generated content.
                </p>
            </div>
        </div>
    </div>
</main>

Local-Guide-App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <div class="container mt-5">
        <h2>@ViewBag.Title</h2>
        <p>We appreciate your feedback and are here to help with any questions you may have.</p>
        <ul class="list-group">
            <li class="list-group-item">
                <i class="fas fa-phone"></i> Phone: <span id="phoneNumber">+1 123-456-7890</span>
            </li>
            <li class="list-group-item">
                <i class="fas fa-envelope"></i> Email: <a href="mailto:support@localguidecms.com">support@localguidecms.com</a>
            </li>
        </ul>
    </div>

</main>

Local-Guide-App/Views/Home/Index.cshtml
@model IEnumerable<Local_Guide_App.Models.LocationDto>

@{
    ViewBag.Title = "Home Page";
}

<main class="container mt-5">
    <div class="row">
        @foreach (var location in Model)
        {
            <div class="col-md-6 mb-4">
                <div class="card">
                    @{
                        string imageurl = "/Content/Images/Locations/default.jpg";
                        if (location.LocationHasPic)
                        {
                            imageurl = "/Content/Images/Locations/" + location.LocationId + "." + location.PicExtension;
                        }
                    }
                    <div class="mb-3">
                        <img class="card-img-top img-fluid" alt="@location.LocationName" src="@imageurl" />
                    </div>

                    <div class="card-body">
                        <h5 class="card-title">@location.LocationName</h5>
                        <p class="card-text">@location.LocationDescription</p>
                        <p class="card-text">Category: @location.Category</p>
                        <p class="card-text">Address: @location.Address</p>
                        <p class="card-text">Average Rating: @location.AverageRating</p>

                        <div class="d-flex justify-content-between">
                            <a href="@Url.Action("Edit", "Location", new { id = location.LocationId })" class="btn btn-warning">Edit Location</a>
                            <a href="@Url.Action("Details", "Location", new { id = location.LocationId })" class="btn btn-info">Details</a>
                            <form action="/Location/Delete" method="post" onsubmit="return confirm('Are you sure you want to delete this location?');">
                                <input type="hidden" name="id" value="@location.LocationId" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</main>